### ISSUE TITLE
Dead links in some Gitbook pages

### ISSUE THREAD

**Issue by interrupt-routine** [MirrorNetworking/MirrorDocs#4]
The following pages of the gitbook have a `See also: <API link> in the API Reference.` header that points to dead links at `https://mirror-networking.com/docs/api/...` instead of `https://storage.googleapis.com/mirror-api-docs/html/...` 

* [Network behaviour](https://mirror-networking.gitbook.io/docs/manual/components/networkbehaviour)
* [Network behaviour callbacks](https://mirror-networking.gitbook.io/docs/manual/guides/communications/networkbehaviour-callbacks)
* [Network identity](https://mirror-networking.gitbook.io/docs/manual/components/network-identity)
* [Network manager callbacks](https://mirror-networking.gitbook.io/docs/manual/guides/communications/networkmanager-callbacks)

**Comment by MrGadget1024** [comment]
These have all been fixed...thanks.
