### ISSUE TITLE
Missing diagram in the "Player Game Objects" page

### ISSUE THREAD

**Issue by interrupt-routine** [MirrorNetworking/MirrorDocs#5]
The [Player Game Objects](https://mirror-networking.gitbook.io/docs/manual/guides/gameobjects/player-gameobjects) page declares:

> The diagram below shows two clients and their local players.

But there is no diagram or image in the page :(

[Markdown source for the page in the repository](https://github.com/MirrorNetworking/MirrorDocs/blob/main/manual/guides/gameobjects/player-gameobjects.md?plain=1)

Perhaps missing a Markdown reference to ![this picture](../blob/main/.gitbook/assets/NetworkLocalPlayers.png) ?

**Comment by MrGadget1024** [comment]
Fixed...thanks
